### PR TITLE
Onboarding documentation update

### PR DESCRIPTION
**Pull request by emma2207**
Ruthlessly getting rid of references to Pennsylvania / UPenn and Google Calendar. 
In some cases it might be worthwhile to add some Colorado / CU specific info.

### CODE REVIEW

**Review by ivichadriana — APPROVED** [review]
Approving. Only Penn related stuff deleted and outdated practices (e.g., tacos)

**Review by klterwelp — APPROVED** [review]
This looks good to me! I think you deleted everything that needed to go.

**Review by cgreene — APPROVED** [review]
Woo! Much updating :)

**Comment by cgreene** [comment]
There was more here that needed to change than I remembered - thank you for doing this!

**Pull request merged**
