### PR TITLE
Some cleanup w/ the move to GitHub

### PR DESCRIPTION
**Pull request by cgreene**

### CODE REVIEW

**Comment by dhimmel** [comment]
Would this be a good opportunity to convert to markdown? In the past, reStructuredText has been one the most frustrating parts of contributing to onboarding.

Or merge this and a new PR with no textual changes?

**Comment by cgreene** [comment]
I'd be happy with a markdown conversion if someone else automates it.

**Comment by dhimmel** [comment]
I can run the files through pandoc in a future PR.

**Review by dhimmel — APPROVED** [review]

**Comment by cgreene** [comment]
Ok - can you pandoc it when you get the chance? I agree that dealing with RST was tough (had the RST docs open yesterday when revising).

**Comment by dhimmel** [comment]
> Ok - can you pandoc it when you get the chance? I agree that dealing with RST was tough (had the RST docs open yesterday when revising).

Yes. Discussion in #2

**Pull request merged**
